/* Normativas FNR: requisitos de cobertura por indicación.
   Texto resumido de las normativas publicadas en fnr.gub.uy; ante duda rige el texto vigente. */
(function(R){
"use strict";
const TRAMITE=[
  'Formulario de Solicitud de Tratamiento (online) completado por el oncólogo tratante',
  'Resumen de historia clínica completo y legible, con evolución y motivos de la indicación (indispensable)',
  'Valoración integral documentada: edad, comorbilidades, calidad de vida y pronóstico → expectativa de vida razonable',
  'Fotocopia de la cédula de identidad del paciente'
];
/* ---------- textos comunes ---------- */
const X={
  qol:'Mala calidad de vida y/o pobre expectativa de vida por comorbilidades',
  card:'HTA no controlada, cardiopatía que contraindique, o FEVI < 50 %',
  psy:'Enfermedad psiquiátrica severa / drogodependencia con evaluación psicológica negativa sobre adherencia',
  psy2:'Patología psiquiátrica o abuso de sustancias que interfiera con controles y adherencia',
  hep:'Hepatopatía con bilirrubina aumentada y transaminasas > 1,5 × LSN',
  cit:'Citopenias severas previas al inicio',
  preg:'Embarazo o lactancia',
  snc:'Metástasis del SNC no controladas con tratamientos previos',
  imm:'Inmunodeficiencia o enfermedad autoinmune activa severa',
  vir:'Infección activa por VHB, VHC y/o VIH',
  neo:'Otra neoplasia maligna no controlada',
  cyp:'Inductores potentes de CYP3A4 en las 3 semanas previas',
  qt:'Prolongación del intervalo QT en el ECG',
  org:'Afección renal, hepática o hematológica significativa',
  epid:'Enfermedad pulmonar intersticial difusa activa o con corticoides recientes'
};
const STD=[X.qol,X.card,X.psy,X.hep,X.cit,X.preg];
const HER2='HER2 positivo: IHQ 3+ o ISH positivo (método validado)';
const RETRAT='Completó 35 ciclos de pembrolizumab sin progresión y progresa ≥ 6 meses después (retratamiento)';

/* ---------- TUMORES ---------- */
const TUMORS=[
/* ======================= MAMA ======================= */
{id:'mama',name:'Mama',sub:'11 indicaciones',src:'Normativa FNR · actualización agosto 2024',
 drugs:'Trastuzumab, pertuzumab, T-DM1, lapatinib, fulvestrant, ribociclib, pembrolizumab',
 groups:[['op','Operable'],['av','Avanzado']],
 para:[
  {t:'Anatomía patológica que confirme carcinoma mamario'},
  {t:'Receptores de estrógeno y progesterona'},
  {t:'HER2/neu en el componente invasor'},
  {t:'PD-L1 con CPS (≥ 10)',only:['m-pembro']},
  {t:'AP de enfermedad residual invasiva con resección completa (R0)',only:['m-adj-tdm1']},
  {t:'Biopsia de metástasis, con RH/HER2',stage:'av',cond:'cuando esté indicada (obligatoria si es lesión única)'},
  {t:'Rx de tórax + ecografía de abdomen, y/o TC de tórax, abdomen y pelvis'},
  {t:'ECG',not:['m-fulv']},
  {t:'Ecocardiograma (ETT) con FEVI que descarte cardiopatía estructural',not:['m-fulv']},
  {t:'Centellograma óseo',stage:'op',cond:'si ≥ 4 ganglios axilares + o sospecha de MTS ósea'},
  {t:'Centellograma óseo',stage:'av',cond:'si sospecha de MTS ósea'},
  {t:'Biopsia de médula ósea',cond:'si sospecha de infiltración medular (anemia normo-normo sin otra causa)'},
  {t:'TC de cráneo y/o RNM',cond:'si síntomas neurológicos'},
  {t:'Hemograma completo'},
  {t:'Funcional y enzimograma hepático completo'},
  {t:'Ionograma'},
  {t:'Creatininemia'},
  {t:'Calcemia',cond:'sólo si secundarismo óseo'},
  {t:'CA 15-3',stage:'av'},
  {t:'Serologías VIH, VHB y VHC',only:['m-pembro']}
 ],
 fu:['Solicitud de dosis del mes siguiente en formulario online, <b>Sistema María</b>, declarando complicaciones y eventos adversos que lleven a discontinuar.','Evaluación de respuesta <b>trimestral por RECIST</b>.','Suspensión: progresión lesional o intolerancia.','Al finalizar/suspender: informar dosis y fecha de la última serie y, si suspende, causa y fecha.','Hepatograma, hemograma, ECG y ecocardiograma seriados a cargo de la institución; reportar cardiotoxicidad que obligue a ajustar o suspender.'],
 inds:[
 {id:'m-neo-t',g:'op',chip:'Trastuzumab',sub:'Neoadyuvancia',title:'Trastuzumab neoadyuvante',setting:'Operable · HER2+',
  proto:[['IV','carga 8 mg/kg → 6 mg/kg c/3 sem, o carga 4 mg/kg → 2 mg/kg semanal'],['SC','600 mg dosis fija c/3 sem'],['Total','neo + adyuvancia: 18 ciclos']],
  inc:['Diagnóstico AP de carcinoma invasor de mama',HER2,'ECOG 0–1','Sin quimioterapia previa','cT ≥ 2 (≥ 2 cm) o cN ≥ 1'],
  exc:['Cáncer de mama metastásico',...STD],
  notes:[['i','La tabla no fija duración propia de la fase neoadyuvante con trastuzumab solo; el tope práctico es el total neo + adyuvancia de 18 ciclos.']]},
 {id:'m-neo-tp',g:'op',chip:'Trastuzumab + Pertuzumab',sub:'Neoadyuvancia',title:'Trastuzumab + Pertuzumab neoadyuvante',setting:'Operable · HER2+',
  proto:[['SC','combinado a dosis fijas: carga T 600 / P 1200 mg → T 600 / P 600 mg c/3 sem'],['Duración','3 a 6 ciclos']],
  inc:['Diagnóstico AP de carcinoma invasor de mama',HER2,'ECOG 0–1','Sin quimioterapia previa',{or:['N ≥ 1','cT ≥ 2 (≥ 2 cm) con cualquier N','Cáncer de mama inflamatorio']}],
  exc:['Cáncer de mama metastásico',...STD],
  notes:[['c','La tabla sólo lista la formulación SC combinada a dosis fijas (no pertuzumab IV).'],['c','Pertuzumab no tiene cobertura en adyuvancia: adyuvancia cubierta = trastuzumab o T-DM1.']]},
 {id:'m-adj-t',g:'op',chip:'Trastuzumab',sub:'Adyuvancia',title:'Trastuzumab adyuvante',setting:'Operable · HER2+',
  proto:[['IV','carga 8 mg/kg → 6 mg/kg c/3 sem'],['SC','600 mg dosis fija c/3 sem'],['Total','neo + adyuvancia: 18 ciclos']],
  inc:['Diagnóstico AP de carcinoma de mama','Axila positiva, o axila negativa con componente invasor ≥ 1 cm',HER2,'ECOG 0–1','< 3 meses desde el fin de la QT adyuvante','Estadificación realizada antes de comenzar la QT'],
  exc:['Cáncer irresecable o con metástasis a distancia',X.qol,'HTA no controlada, cardiopatía que contraindique, o FEVI < 50 % luego de QT adyuvante con antraciclinas',X.psy,X.hep,X.cit,X.preg],
  indv:['Tumores < 10 mm pero con estadios avanzados'],
  notes:[['i','El plazo de < 3 meses se cuenta desde la última dosis de QT: consignar la fecha exacta en el resumen.']]},
 {id:'m-adj-tdm1',g:'op',chip:'T-DM1',sub:'Adyuvancia post-neo',title:'T-DM1 adyuvante (enfermedad residual)',setting:'Operable · HER2+ · residual invasivo post-neoadyuvancia',
  proto:[['IV','3,6 mg/kg c/3 sem'],['Total','neo + adyuvancia: 18 ciclos']],
  inc:['Diagnóstico AP de carcinoma invasor de mama','Axila positiva, o axila negativa con componente invasor ≥ 1 cm',HER2,'ECOG 0–1','Neoadyuvancia previa con ≥ 4 ciclos de trastuzumab (± pertuzumab) + taxanos','Carcinoma invasivo residual en mama o axila tras neoadyuvancia y cirugía','Cirugía completa R0 de la enfermedad residual','≤ 12 semanas entre la cirugía y la solicitud'],
  exc:['Cáncer localmente avanzado y/o con metástasis a distancia',...STD],
  notes:[['i','“Loco-regionalmente avanzado” no aclara si es al diagnóstico o post-cirugía. KATHERINE incluyó cT4 y N2–3; leído literalmente, un cT4 quedaría afuera. Aclararlo en el resumen o consultar al FNR.'],['i','“18 ciclos neo + adyuvancia” no coincide con los 14 ciclos de T-DM1 de KATHERINE; leerlo como tope total anti-HER2.'],['c','Las 12 semanas corren desde la cirugía hasta la solicitud, no hasta el inicio.']]},
 {id:'m-av-tp',g:'av',chip:'Trastuzumab ± Pertuzumab',sub:'HER2+ · 1ª línea',title:'Trastuzumab ± Pertuzumab avanzado',setting:'Avanzado · HER2+',
  proto:[['IV','trastuzumab carga 8 → 6 mg/kg c/3 sem'],['SC','trastuzumab 600 mg c/3 sem; o T + P combinado 600/1200 → 600/600 mg c/3 sem'],['Duración','hasta progresión, intolerancia o indicación médica'],['Asociado','a plan de QT validado']],
  inc:['Diagnóstico AP de carcinoma de mama HER2+ (IHQ 3+ o ISH+), en primario y en metástasis si fue biopsiada','Enfermedad a distancia, confirmada por biopsia si es lesión única','ECOG 0–1','Previsión de que tolerará dosis y frecuencia del protocolo','Sin QT previa por enfermedad metastásica'],
  exc:[X.qol,'Recaída < 12 meses de finalizado trastuzumab',X.snc,X.card,X.psy,X.hep,X.cit,X.preg],
  notes:[['c','Si recayó < 12 meses post-trastuzumab, la vía de cobertura es T-DM1.'],['c','Trastuzumab deruxtecán y tucatinib no están en esta normativa.']]},
 {id:'m-av-tdm1',g:'av',chip:'T-DM1',sub:'HER2+ · 2ª línea',title:'T-DM1 avanzado',setting:'Avanzado · HER2+',
  proto:[['IV','3,6 mg/kg c/3 sem'],['Duración','hasta progresión, intolerancia o indicación médica']],
  inc:['Diagnóstico AP de carcinoma de mama','Enfermedad a distancia, confirmada por biopsia si es lesión única',HER2+'; en primario y en metástasis si fue biopsiada',{or:['Progresión tras 1ª o 2ª línea anti-HER2 (trastuzumab, T + P, o lapatinib + QT)','Recaída o progresión durante la adyuvancia o ≤ 12 meses de finalizada','Contraindicación o intolerancia a los anti-HER2 anteriores']},'ECOG 0–1','Previsión de que tolerará dosis y frecuencia del protocolo'],
  exc:[X.qol,'Secundarismo encefálico no controlado',X.card,X.psy,X.hep,X.cit,X.preg],
  notes:[['i','Los tres escenarios figuran como viñetas separadas; por lógica clínica son alternativas, no acumulativos.']]},
 {id:'m-lap',g:'av',chip:'Lapatinib',sub:'HER2+',title:'Lapatinib avanzado',setting:'Avanzado · HER2+',
  proto:[['VO','1250 mg/día'],['Duración','hasta progresión, intolerancia o indicación médica'],['Asociado','a plan de QT validado']],
  inc:['Diagnóstico AP de carcinoma de mama HER2+ (IHQ 3+ o ISH+), en primario y en metástasis si fue biopsiada',{or:['Contraindicación o intolerancia a los otros anti-HER2','Progresión encefálica con los tratamientos previos (independiente de otras localizaciones)']},'ECOG 0–1','Previsión de que tolerará dosis y frecuencia del protocolo'],
  exc:STD,
  notes:[['i','Las dos condiciones de entrada se leen como alternativas; si el caso cumple sólo una, explicitarlo.'],['c','1250 mg/día es la dosis de la combinación con capecitabina.']]},
 {id:'m-fulv',g:'av',chip:'Fulvestrant',sub:'RH+',title:'Fulvestrant avanzado',setting:'Avanzado · RH+ · postmenopáusica',
  proto:[['IM','500 mg días 0, 14 y 28, luego 500 mg mensual'],['Duración','hasta progresión, intolerancia o indicación médica']],
  inc:['Diagnóstico AP de carcinoma de mama RH+ en paciente postmenopáusica','Enfermedad a distancia, confirmada por biopsia si es lesión única','Resistencia a tamoxifeno y/o IA','ECOG 0–1'],
  exc:[X.qol,X.snc,X.psy],
  notes:[['c','ECG y ecocardiograma no son necesarios para fulvestrant.'],['c','La tabla también lista 250 mg mensual, dosis superada desde CONFIRM.'],['i','La nota al pie “asociados a planes de QT validados” no aplica a fulvestrant ni a ribociclib: error de redacción.']]},
 {id:'m-ribo1',g:'av',chip:'Ribociclib',sub:'RH+/HER2− · 1ª línea',title:'Ribociclib 1ª línea',setting:'Avanzado · RH+ · HER2−',
  proto:[['VO','ribociclib 600 mg/día + IA o tamoxifeno'],['HT adyuv. < 12 m','ribociclib 600 mg/día + fulvestrant 500 mg d0, 14, 28 → mensual'],['Duración','hasta progresión, intolerancia o indicación médica']],
  inc:['Diagnóstico AP de carcinoma de mama RH+','HER2 negativo','Enfermedad a distancia, confirmada por biopsia si es lesión única','Sin QT ni HT previa por enfermedad avanzada (adyuvante permitida)','En combinación con HT (tamoxifeno o IA)','Si recibe o recibió HT adyuvante en los últimos 12 meses y progresa → combinar con fulvestrant','ECOG 0–1'],
  exc:[X.qol,X.snc,'QT previa (salvo neo/adyuvancia), fulvestrant o iCDK4/6 previo','Cáncer de mama inflamatorio al diagnóstico',X.card,X.psy,X.preg],
  indv:['ECOG 2'],
  notes:[['i','Las exclusiones y el ECOG 2 aparecen después de la 2ª línea; se leen como comunes a ambas.'],['i','No menciona supresión ovárica en premenopáusicas ni el esquema 21/7: consignar ambos en la solicitud.'],['c','ECG basal exigido: relevante por prolongación del QT.']]},
 {id:'m-ribo2',g:'av',chip:'Ribociclib + Fulvestrant',sub:'RH+/HER2− · 2ª línea',title:'Ribociclib + Fulvestrant 2ª línea',setting:'Avanzado · RH+ · HER2−',
  proto:[['VO/IM','ribociclib 600 mg/día + fulvestrant 500 mg d0, 14, 28 → mensual'],['Duración','hasta progresión, intolerancia o indicación médica']],
  inc:['Diagnóstico AP de carcinoma de mama RH+','HER2 negativo','Enfermedad a distancia, confirmada por biopsia si es lesión única','Resistencia a tamoxifeno y/o IA','Sin QT previa por enfermedad avanzada','En combinación con fulvestrant','ECOG 0–1'],
  exc:[X.qol,X.snc,'QT previa (salvo neo/adyuvancia), fulvestrant o iCDK4/6 previo','Cáncer de mama inflamatorio al diagnóstico',X.card,X.psy,X.preg],
  indv:['ECOG 2'],
  notes:[['c','Fulvestrant previo excluye.']]},
 {id:'m-pembro',g:'av',chip:'Pembrolizumab',sub:'Triple negativo · 1ª línea',title:'Pembrolizumab triple negativo avanzado',setting:'Avanzado · RE−, RP−, HER2− · PD-L1 CPS ≥ 10',
  proto:[['IV','200 mg c/3 sem'],['Duración','35 ciclos'],['Asociado','nab-paclitaxel, paclitaxel o gemcitabina/carboplatino u otro plan validado']],
  inc:['Diagnóstico AP de carcinoma de mama con RE y RP negativos','HER2 negativo','Enfermedad locorregional irresecable o a distancia, biopsia si es lesión única','PD-L1 positivo con CPS ≥ 10 por método validado','Sin QT previa por enfermedad avanzada; si recibió neo/adyuvancia, intervalo libre > 6 meses','En combinación con plan de QT validado'],
  exc:[X.imm,X.snc,X.vir,X.neo,X.preg,X.psy2,'Pembrolizumab previo con progresión'],
  indv:['Enfermedad autoinmune activa que requiera tratamiento sistémico','Trasplante de MO y/o de órgano sólido','ECOG 2',RETRAT,'Recaída precoz (< 6 meses) tras tratamiento neo/adyuvante'],
  notes:[['c','Sólo enfermedad avanzada: el esquema KEYNOTE-522 (temprano) no está cubierto.'],['i','La recaída < 6 meses no excluye automáticamente: es caso individualizado.'],['i','El umbral CPS ≥ 10 proviene de 22C3 en KEYNOTE-355: conviene que el informe especifique el clon.']]}
 ]},

/* ======================= COLORRECTO ======================= */
{id:'ccr',name:'Colorrecto',sub:'3 indicaciones',src:'Normativa FNR · octubre 2024',
 drugs:'Bevacizumab, cetuximab, pembrolizumab',
 groups:[['met','Metastásico']],
 para:[
  {t:'AP que demuestre adenocarcinoma colorrectal'},
  {t:'Biopsia de la metástasis',cond:'si metástasis única'},
  {t:'CEA y CA 19-9'},
  {t:'Imagenología de tórax, abdomen y pelvis'},
  {t:'ECG'},
  {t:'Ecocardiograma (ETT) con FEVI'},
  {t:'Centellograma óseo',cond:'si sospecha de MTS ósea'},
  {t:'TC de cráneo con contraste y/o RNM',cond:'si sospecha de secundarismo o MTS encefálicas tratadas'},
  {t:'Hemograma completo'},
  {t:'Crasis'},
  {t:'Funcional y enzimograma hepático'},
  {t:'Creatininemia'},
  {t:'Examen de orina; si proteinuria: orina de 24 h o índice proteinuria/creatininuria'},
  {t:'KRAS, NRAS y BRAF',only:['c-cetux']},
  {t:'Ionograma con magnesio',only:['c-cetux']},
  {t:'MSI / dMMR por método validado',only:['c-pembro']},
  {t:'Serologías VIH, VHB y VHC',only:['c-pembro']},
  {t:'TSH y despistaje de tuberculosis',only:['c-pembro'],sug:true},
  {t:'Vacunación según pautas MSP para grupos de riesgo',sug:true}
 ],
 fu:['Solicitud de dosis del mes siguiente online, <b>Sistema María</b>. Efectos adversos se reportan con la solicitud; ajustes de dosis en el formulario DPP con motivo.','Evaluación <b>trimestral por RECIST</b>; en estables prolongados puede espaciarse la imagen y seguir con marcadores.','Bevacizumab: ante la 1ª progresión puede rotarse la QT manteniéndolo; se suspende si progresa con la QT ya rotada o por intolerancia.','Cetuximab y pembrolizumab: suspender por progresión o intolerancia; pembrolizumab hasta 35 ciclos.'],
 inds:[
 {id:'c-bev',g:'met',chip:'Bevacizumab',sub:'1ª o 2ª línea + QT',title:'Bevacizumab en CCR metastásico',setting:'Metastásico · 1ª o 2ª línea, asociado a QT',
  proto:[['IV','5 mg/kg en planes c/15 días'],['IV','7,5 mg/kg en planes c/21 días'],['Asociado','a esquemas de QT válidos'],['Progresión','1ª progresión: puede rotarse QT y mantener bevacizumab']],
  inc:['Diagnóstico AP de cáncer colorrectal','Enfermedad a distancia, confirmada por biopsia si es lesión única','ECOG 0–1','Enfermedad medible por RECIST 1.1','Función hepática, renal, hematológica y crasis aceptables','1ª o 2ª línea, en combinación con QT','En 2ª línea: sin progresión previa a cetuximab ni a inmunoterapia'],
  exc:[X.snc,X.psy,X.preg,X.neo,'HTA o enfermedad cardiovascular significativa no controladas','Síndrome nefrótico, proteinuria ≥ 500 mg/24 h y/o deterioro renal significativo'],
  indv:['ECOG 2','Síndrome hemorragíparo, anticoagulación o antiagregación'],
  notes:[['c','No se cubre en 2ª línea luego de progresión a cetuximab ni a inmunoterapia.'],['c','Continuidad tras 1ª progresión cubierta rotando la QT (suspensión recién con progresión bajo la QT rotada).'],['c','Panitumumab, aflibercept y encorafenib no están en esta normativa.']]},
 {id:'c-cetux',g:'met',chip:'Cetuximab',sub:'1ª línea · izquierdo RAS/BRAF wt',title:'Cetuximab en CCR metastásico',setting:'Metastásico · colon izquierdo o recto · RAS y BRAF no mutados · 1ª línea',
  proto:[['IV','400 mg/m² → 250 mg/m² semanal'],['IV','400 → 250 mg/m² semanal, ciclos de 28 días con 21 de tratamiento'],['IV','500 mg/m² c/2 sem'],['Asociado','únicamente a plan con irinotecán']],
  inc:['Diagnóstico AP de cáncer de colon izquierdo o recto','Enfermedad a distancia, confirmada por biopsia si es lesión única','ECOG 0–1','Enfermedad medible por RECIST 1.1','Función hepática, renal, hematológica y crasis aceptables','KRAS, NRAS y BRAF no mutados','Sin tratamiento sistémico previo para la enfermedad metastásica','Asociado a plan con irinotecán'],
  exc:[X.snc,X.psy,X.preg,X.neo],
  indv:['ECOG 2'],
  notes:[['c','Sólo con irinotecán: FOLFOX + cetuximab no está cubierto.'],['i','“Colon izquierdo” no está definido; usar la convención ángulo esplénico hacia distal y consignarlo.'],['i','La introducción menciona sobreexpresión de EGFR, pero no es criterio de inclusión ni se pide en paraclínica.']]},
 {id:'c-pembro',g:'met',chip:'Pembrolizumab',sub:'1ª línea · dMMR / MSI-H',title:'Pembrolizumab en CCR dMMR/MSI-H',setting:'Metastásico · dMMR o MSI-H · 1ª línea',
  proto:[['IV','200 mg c/3 sem'],['Duración','35 ciclos']],
  inc:['Diagnóstico AP de cáncer colorrectal','Enfermedad a distancia, confirmada por biopsia si es lesión única','ECOG 0–1','Enfermedad medible por RECIST 1.1','Función hepática, renal, hematológica y crasis aceptables','dMMR o MSI-H','Sin tratamiento sistémico previo para la enfermedad metastásica'],
  exc:[X.snc,X.psy,X.preg,X.neo,X.imm,X.vir],
  indv:['ECOG 2','Enfermedad autoinmune con inmunosupresión sistémica',RETRAT],
  notes:[['i','No indica asociación con QT: corresponde a monoterapia (KEYNOTE-177).'],['c','Sólo 1ª línea: un dMMR ya tratado con QT por enfermedad metastásica no entra.']]}
 ]},

/* ======================= PRÓSTATA ======================= */
{id:'pros',name:'Próstata',sub:'3 indicaciones',src:'Normativa FNR · octubre 2024',
 drugs:'Abiraterona, olaparib',
 groups:[['hs','Sensible a castración'],['cr','Resistente a castración']],
 para:[
  {t:'AP completa que confirme adenocarcinoma prostático'},
  {t:'Testosterona que documente castración (≤ 50 ng/dl)',not:['p-hspc']},
  {t:'Testosterona',only:['p-hspc'],cond:'la normativa la pide sin distinguir; en CPSCm documenta la TDA'},
  {t:'Curva de PSA con valor actual'},
  {t:'BRCA1, BRCA2 y/o ATM',only:['p-ola']},
  {t:'Imagenología de tórax, abdomen y pelvis'},
  {t:'Centellograma óseo'},
  {t:'Imagen de cráneo',cond:'si sospecha clínica de secundarismo encefálico'},
  {t:'Ionograma con calcemia',cond:'requerido si MTS óseas'},
  {t:'Funcional hepático'},
  {t:'Hemograma'},
  {t:'Azoemia'},
  {t:'Creatininemia'},
  {t:'ECG'},
  {t:'Ecocardiograma (ETT)'}
 ],
 fu:['Solicitud de dosis del mes siguiente online a través del <b>Portal</b>, declarando complicaciones y eventos adversos.','Evaluación <b>cada 3 meses</b>: curva de PSA actualizada, imagen e informe del oncólogo.','Suspensión: progresión (RECIST, clínica o PSA según PCWG3) o intolerancia.','Mantener análogo de LHRH en no orquiectomizados.'],
 inds:[
 {id:'p-hspc',g:'hs',chip:'Abiraterona',sub:'CPSCm',title:'Abiraterona en CPSC metastásico',setting:'Metastásico sensible a castración',
  proto:[['VO','1000 mg/día en una toma, alejado de comidas'],['Prednisona','5 mg/día'],['TDA','mantener análogo LHRH si no hay castración quirúrgica'],['Duración','hasta progresión o intolerancia']],
  inc:['Adenocarcinoma prostático metastásico','ECOG ≤ 2',{or:['Debut metastásico (visceral u óseo)','Metacrónico con ≥ 2 de: Gleason ≥ 8 · ≥ 3 lesiones óseas · MTS visceral']}],
  exc:[X.qol,'Metástasis encefálicas no controladas','Afectación renal, hepática y/o hematológica significativa','HTA no controlada u otra enfermedad cardiovascular significativa','Insuficiencia pituitaria o suprarrenal conocida','Tratamiento previo con ketoconazol','Abiraterona u otro inhibidor CYP17 previo','Infección severa en curso'],
  indv:['Ausencia de confirmación anatomopatológica','Hasta 3 ciclos de QT previos para la enfermedad avanzada'],
  notes:[['i','El encabezado habla de “alto riesgo”, pero el criterio de debut metastásico no exige factores de riesgo (LATITUDE sí). En un de novo de bajo volumen, explicitarlo en el resumen.'],['i','Triplete con docetaxel completo: sólo contempla hasta 3 ciclos de QT previa y como caso individualizado.'],['c','Enzalutamida, apalutamida y darolutamida no están en esta normativa.']]},
 {id:'p-crpc',g:'cr',chip:'Abiraterona',sub:'CPRCm',title:'Abiraterona en CPRC metastásico',setting:'Metastásico resistente a castración',
  proto:[['VO','1000 mg/día en una toma, alejado de comidas'],['Prednisona','5 mg c/12 h'],['TDA','mantener análogo LHRH si no hay castración quirúrgica'],['Duración','hasta progresión o intolerancia']],
  inc:['Adenocarcinoma prostático metastásico','ECOG ≤ 2','Testosterona en rango de castración (≤ 50 ng/dl o 2 nmol/l)','Progresión: 2 aumentos consecutivos de PSA desde un valor de referencia y/o progresión radiológica ósea o de partes blandas'],
  exc:[X.qol,'Metástasis encefálicas no controladas','Afectación renal, hepática y/o hematológica significativa','HTA no controlada u otra enfermedad cardiovascular significativa','Insuficiencia pituitaria o suprarrenal conocida','Tratamiento previo con ketoconazol','Abiraterona u otro inhibidor CYP17 previo','Infección severa en curso'],
  indv:['Ausencia de confirmación anatomopatológica'],
  notes:[['c','Si recibió abiraterona en CPSCm, no hay nueva cobertura en CPRCm (inhibidor CYP17 previo).']]},
 {id:'p-ola',g:'cr',chip:'Olaparib',sub:'CPRCm · BRCA/ATM',title:'Olaparib en CPRC metastásico',setting:'Metastásico resistente a castración · BRCA1/2 y/o ATM',
  proto:[['VO','monoterapia 300 mg c/12 h continuo'],['Combinado','olaparib 300 mg c/12 h + abiraterona 1000 mg/día + prednisona 5 mg c/12 h'],['TDA','mantener análogo LHRH'],['Duración','hasta progresión o intolerancia']],
  inc:['Adenocarcinoma prostático metastásico','Testosterona en rango de castración (≤ 50 ng/dl o 2 nmol/l)','Progresión bioquímica y/o radiográfica a hormonoterapia','Mutación BRCA1, BRCA2 y/o ATM','ECOG ≤ 2'],
  exc:['Inhibidor de PARP previo, incluido olaparib',X.qol,'Metástasis encefálicas no controladas','Afectación renal, hepática y/o hematológica significativa','HTA no controlada u otra enfermedad cardiovascular significativa','QT prolongado en el ECG','Infección activa por VIH, VHB o VHC','Infección severa en curso'],
  indv:['Ausencia de confirmación anatomopatológica','Trasplante alogénico de médula ósea'],
  notes:[['c','Excluye infección activa por VIH/VHB/VHC, pero las serologías no están en la lista de paraclínica: enviarlas evita objeciones.'],['i','Para la combinación con abiraterona valen razonablemente también las exclusiones de abiraterona (CYP17 previo).'],['i','“Progresión a hormonoterapia” no exige un nuevo agente hormonal (PROfound sí): consignar la secuencia previa.']]}
 ]},

/* ======================= PULMÓN ======================= */
{id:'pulm',name:'Pulmón',sub:'6 indicaciones',src:'Normativa FNR · setiembre 2025',
 drugs:'Osimertinib, erlotinib, gefitinib, alectinib, pembrolizumab, atezolizumab, bevacizumab',
 groups:[['res','Resecado'],['av','Avanzado']],
 para:[
  {t:'AP completa de carcinoma broncopulmonar a células no pequeñas'},
  {t:'EGFR (método validado): mutación sensibilizante y ausencia de mutaciones de resistencia',only:['u-1g']},
  {t:'EGFR con Ex19del o L858R',only:['u-adj','u-osi']},
  {t:'ALK positivo',only:['u-alec'],cond:'criterio de inclusión; no figura en la lista de paraclínica'},
  {t:'EGFR y ALK sin alteraciones (método validado)',only:['u-io','u-abcp']},
  {t:'PD-L1 (método validado): ≥ 50 % atezolizumab · ≥ 1 % pembrolizumab',only:['u-io']},
  {t:'PD-L1 positivo < 50 % (método validado)',only:['u-abcp']},
  {t:'TC y/o RNM de tórax y abdomen'},
  {t:'ECG'},
  {t:'Ecocardiograma (ETT) con FEVI que excluya cardiopatía estructural'},
  {t:'Centellograma óseo',cond:'si sospecha de MTS ósea'},
  {t:'RNM / TC de cráneo',cond:'si síntomas: descartar secundarismo no controlado'},
  {t:'Hemograma completo'},
  {t:'Crasis'},
  {t:'Funcional y enzimograma hepático completo'},
  {t:'Serologías VIH, VHB y VHC'},
  {t:'Creatininemia (función renal)'},
  {t:'Ionograma con calcemia'},
  {t:'Examen de orina; si proteinuria: orina de 24 h o índice proteinuria/creatininuria',only:['u-abcp']}
 ],
 fu:['Solicitud de dosis del mes siguiente online, declarando complicaciones y eventos adversos.','Evaluación RECIST: <b>adyuvancia cada 6 meses</b>, <b>irresecable trimestral</b>.','Suspensión: progresión, intolerancia o eventos adversos grado III–IV.','No se acepta cambio de fármaco por progresión (salvo las excepciones de ITK de 1ª generación).'],
 inds:[
 {id:'u-adj',g:'res',chip:'Osimertinib',sub:'Adyuvancia · EGFR+',title:'Osimertinib adyuvante',setting:'CPCNP resecado · estadio IIIA · EGFR Ex19del / L858R',
  proto:[['VO','80 mg/día'],['Duración','máximo 3 años o hasta progresión / toxicidad inaceptable'],['Evaluación','cada 6 meses']],
  inc:['Diagnóstico AP de CPCNP','Estadio IIIA','EGFR Ex19del o L858R (± otras mutaciones, incluida T790M)','Resección completa del primario con márgenes libres','Entre 4 y 10 semanas post-cirugía, con recuperación adecuada','ECOG 0–1'],
  exc:['QT neoadyuvante previa',X.cyp,X.snc,X.imm,X.vir,X.neo,X.qt,X.epid,X.org,X.preg,X.psy2,'Osimertinib previo con progresión'],
  indv:['Más de 10 semanas desde la cirugía','ECOG 2'],
  notes:[['c','Sólo estadio IIIA: IB–II (incluidos en ADAURA) no están cubiertos.'],['i','Las exclusiones figuran bajo 1ª línea, pero incluyen “neoadyuvancia con QT en resecable”: se leen como comunes.'],['i','Si hace QT adyuvante primero, la ventana de 10 semanas se vence: queda como caso individualizado.']]},
 {id:'u-1g',g:'av',chip:'Erlotinib / Gefitinib',sub:'EGFR+ · 1ª línea',title:'Erlotinib o gefitinib 1ª línea',setting:'CPCNP IIIB no operable o IV · EGFR mutación activadora',
  proto:[['VO','erlotinib 150 mg/día'],['VO','gefitinib 250 mg/día'],['Duración','hasta progresión o toxicidad inaceptable']],
  inc:['Diagnóstico AP de CPCNP','Estadio IIIB no operable o IV','Mutación activadora de EGFR asociada a buena respuesta','Sin tratamiento sistémico previo por enfermedad avanzada','ECOG 0–1'],
  exc:[X.snc,X.cyp,'Mutación de resistencia (p. ej. T790M)',X.neo,'Patología intestinal u oftalmológica significativa','Enfermedad autoinmune activa severa','Cardiopatía significativa o arritmias ventriculares con medicación',X.epid,X.psy2,X.org,X.preg,'Alguno de estos fármacos previo con progresión'],
  indv:['ECOG 2'],
  notes:[['c','Osimertinib 1ª línea exige Ex19del o L858R; las mutaciones infrecuentes sensibilizantes sólo entran por esta vía.'],['c','Progresión con T790M bajo erlotinib/gefitinib → osimertinib como caso individualizado.']]},
 {id:'u-osi',g:'av',chip:'Osimertinib',sub:'EGFR+ · 1ª línea',title:'Osimertinib 1ª línea',setting:'CPCNP irresecable · EGFR Ex19del / L858R',
  proto:[['VO','80 mg/día'],['Duración','hasta progresión o toxicidad inaceptable']],
  inc:['Diagnóstico AP de CPCNP','Irresecable (localmente avanzado o metastásico)','EGFR Ex19del o L858R (± otras, incluida T790M)','Sin tratamiento sistémico previo para la enfermedad avanzada','Tumor medible por RECIST','ECOG 0–1'],
  exc:[X.cyp,X.snc,X.imm,X.vir,X.neo,X.qt,X.epid,X.org,X.preg,X.psy2,'Osimertinib previo con progresión'],
  indv:['ECOG 2','En curso con gefitinib/erlotinib y estabilidad lesional (cambio permitido hasta 6 meses de iniciada esta cobertura)','Progresión bajo gefitinib/erlotinib con T790M'],
  notes:[['i','La ventana de cambio desde gefitinib/erlotinib (6 meses desde el inicio de la cobertura, normativa setiembre 2025) probablemente ya venció: confirmar con el FNR.'],['c','Osimertinib + QT (FLAURA2) no figura en el protocolo.']]},
 {id:'u-alec',g:'av',chip:'Alectinib',sub:'ALK+ · 1ª línea',title:'Alectinib 1ª línea',setting:'CPCNP irresecable · ALK positivo',
  proto:[['VO','600 mg c/12 h'],['Duración','hasta progresión o toxicidad inaceptable']],
  inc:['Diagnóstico AP de CPCNP','Irresecable (localmente avanzado o metastásico)','ALK positivo','Tumor medible por RECIST','Sin tratamiento sistémico previo para la enfermedad avanzada','ECOG 0–2'],
  exc:[X.cyp,X.snc,X.imm,X.vir,X.neo,X.qt,X.org,X.preg,X.psy2,'Alectinib previo con progresión'],
  indv:['Trasplante de órgano sólido previo'],
  notes:[['c','ECOG 2 entra directo (no individualizado), a diferencia del resto.'],['c','El estudio de ALK no está en la lista de paraclínica, pero es criterio de inclusión: enviarlo.'],['c','Crizotinib, lorlatinib, brigatinib y otros drivers (ROS1, KRAS G12C…) no están en esta normativa.']]},
 {id:'u-io',g:'av',chip:'Pembrolizumab / Atezolizumab',sub:'Sin driver · 1ª línea',title:'Pembrolizumab o atezolizumab 1ª línea',setting:'CPCNP IIIB no operable o IV · EGFR y ALK negativos',
  proto:[['IV','pembrolizumab 200 mg c/3 sem, hasta 35 ciclos'],['IV','atezolizumab 1200 mg c/3 sem'],['SC','atezolizumab 1875 mg c/3 sem'],['Duración','atezolizumab hasta progresión o toxicidad']],
  inc:['Diagnóstico AP de CPCNP','Primera línea (sin tratamiento sistémico previo)','Estadio IIIB no operable o IV','EGFR y ALK negativos',{or:['Pembrolizumab: PD-L1 positivo (≥ 1 %)','Atezolizumab: PD-L1 ≥ 50 %'],label:'Según el fármaco'},'ECOG 0–1'],
  exc:[X.imm,X.snc,X.vir,X.neo,X.preg,X.psy2,'El mismo fármaco previo con progresión'],
  indv:['Enfermedad autoinmune activa que requiera tratamiento sistémico','Trasplante de MO y/o de órgano sólido','ECOG 2',RETRAT],
  notes:[['i','El protocolo lista pembrolizumab sin QT y exige PD-L1 positivo: pembrolizumab + QT en PD-L1 < 1 % (KEYNOTE-189/407) no queda cubierto. Si piensa asociarlo a QT, confirmar con el FNR.'],['c','Escamoso con PD-L1 < 1 %: sin opción de inmunoterapia en esta normativa (ABCP es sólo no escamoso).']]},
 {id:'u-abcp',g:'av',chip:'ABCP',sub:'No escamoso · PD-L1 1–49 %',title:'Atezolizumab + Bevacizumab + QT (ABCP)',setting:'CPCNP no escamoso estadio IV · EGFR y ALK negativos · PD-L1 positivo < 50 %',
  proto:[['IV/SC','atezolizumab 1200 mg IV o 1875 mg SC c/3 sem'],['IV','bevacizumab 15 mg/kg c/3 sem'],['Asociado','carboplatino + paclitaxel'],['Duración','hasta progresión o toxicidad inaceptable']],
  inc:['Diagnóstico AP de CPCNP de histología no escamosa','Primera línea de tratamiento sistémico','Estadio IV','EGFR y ALK negativos','PD-L1 positivo, menor a 50 %','ECOG 0–1'],
  exc:[X.imm,X.snc,X.vir,X.neo,X.preg,X.psy2,'El mismo fármaco previo con progresión','HTA o enfermedad cardiovascular significativa no controlada','Enfermedad renal significativa no controlada'],
  indv:['Enfermedad autoinmune activa que requiera tratamiento sistémico','Trasplante de MO y/o de órgano sólido','ECOG 2',RETRAT,'Síndrome hemorragíparo, anticoagulación o antiagregación'],
  notes:[['i','La introducción dice “independientemente de PD-L1”, pero la inclusión exige PD-L1 positivo < 50 %: PD-L1 negativo queda afuera por texto.'],['c','Sólo estadio IV (no IIIB).']]}
 ]},

/* ======================= CUELLO UTERINO ======================= */
{id:'ccu',name:'Cuello uterino',sub:'1 indicación',src:'Normativa FNR · octubre 2024',
 drugs:'Pembrolizumab',
 groups:[['av','Avanzado']],
 para:[
  {t:'AP completa que confirme cáncer de cuello uterino'},
  {t:'PD-L1 con CPS ≥ 1 (método validado)'},
  {t:'Imagenología de tórax, abdomen y pelvis'},
  {t:'Informe del especialista que certifique la irresecabilidad'},
  {t:'Ionograma con calcemia'},
  {t:'Funcional hepático'},
  {t:'Hemograma'},
  {t:'Azoemia'},
  {t:'Creatininemia'},
  {t:'Serologías VIH, VHB y VHC (si positiva: informe de infectólogo que avale el tratamiento)'},
  {t:'Ecocardiograma (ETT)'},
  {t:'Funcional respiratorio',sug:true},
  {t:'Perfil tiroideo',sug:true}
 ],
 fu:['Solicitud de dosis del mes siguiente online a través del <b>Portal</b>, declarando complicaciones y eventos adversos.','Evaluación <b>trimestral</b>: TC o RNM + informe del oncólogo con la respuesta clínica.','Suspensión: progresión o intolerancia.','Las instituciones que no envíen la información requerida pueden quedar excluidas de nuevos tratamientos.'],
 inds:[
 {id:'u-ccu',g:'av',chip:'Pembrolizumab',sub:'1ª línea · CPS ≥ 1',title:'Pembrolizumab en cuello uterino avanzado',setting:'Persistente, recurrente o metastásico · irresecable · 1ª línea sistémica',
  proto:[['IV','200 mg c/21 días'],['Duración','hasta progresión o toxicidad, máximo 35 ciclos'],['Asociado','protocolo validado con sales de platino + taxano']],
  inc:['Cáncer de cuello uterino persistente, recurrente o metastásico','Primera línea de tratamiento sistémico','PD-L1 con CPS ≥ 1','Enfermedad medible por RECIST','ECOG 0–1'],
  exc:[X.snc,X.imm,X.vir,X.neo,X.preg,X.psy2],
  indv:['ECOG 2'],
  notes:[['c','El protocolo cubre platino + taxano; bevacizumab (opcional en KEYNOTE-826) no figura en la cobertura.'],['c','Pide ecocardiograma pero no ECG.'],['c','Localmente avanzado con quimiorradioterapia (KEYNOTE-A18) no está cubierto.'],['c','El informe de irresecabilidad del especialista es requisito de paraclínica: fácil de olvidar.']]}
 ]}
];

R.fnr={TUMORS:TUMORS,TRAMITE:TRAMITE};
})(window.FNRO=window.FNRO||{});
